# Default Chemisty Kit Configuration File

base_url: http://google.com
retries_on_failure: 1 #defaults to 1, set the number of times a test should be retried on failure
concurrency: 1
log:
    path: #you may override the default log path 'evidence'
    results_file: #you may override the default file name 'results_junit.xml'
    format: #you may override the default format 'junit'
selenium_connect:
    #Setup & Debugging
    jar:

    #Where to run your tests
    host: 'localhost'
    port: #set to 4444 by default

    #Browser & Host
    browser:      'firefox'
    browser_path:
    profile_path:
    profile_name:

    #Saucelabs
    sauce_username:
    sauce_api_key:
    api_timeout:
    sauce_opts:
        os:
        browser_version:
        job_name:
