base_url: http://google.com
screenshot_on_fail: true
selenium_connect:
    host:             'saucelabs'
    browser:          'firefox'
    browser_version:  '17'
    sauce_username:   'testing_arrgyle'
    sauce_api_key:    'ab7a6e17-16df-42d2-9ef6-c8d2539cc38a'
